"""The corpus: one pinned 10-K per company, stored in `ingest/corpus.toml`.

Filings are pinned by accession number so the corpus (and the eval golden set built on it)
never drifts when companies publish new reports. Re-pin deliberately with:

    python -m ingest.corpus resolve
"""

from __future__ import annotations

import argparse
import asyncio
import tomllib
from dataclasses import dataclass
from datetime import date
from pathlib import Path

from common.config import get_settings
from ingest.edgar import ARCHIVE_URL, EdgarClient

CORPUS_PATH = Path(__file__).parent / "corpus.toml"

# (ticker, CIK, display name). CIKs are pinned explicitly: tickers can move between legal
# entities (e.g. XOM now maps to "ExxonMobil Holdings Corp", which has no 10-K yet).
COMPANIES: list[tuple[str, int, str]] = [
    ("AAPL", 320193, "Apple Inc."),
    ("MSFT", 789019, "Microsoft Corporation"),
    ("AMZN", 1018724, "Amazon.com, Inc."),
    ("GOOGL", 1652044, "Alphabet Inc."),
    ("META", 1326801, "Meta Platforms, Inc."),
    ("NVDA", 1045810, "NVIDIA Corporation"),
    ("JPM", 19617, "JPMorgan Chase & Co."),
    ("BAC", 70858, "Bank of America Corporation"),
    ("GS", 886982, "The Goldman Sachs Group, Inc."),
    ("JNJ", 200406, "Johnson & Johnson"),
    ("PFE", 78003, "Pfizer Inc."),
    ("UNH", 731766, "UnitedHealth Group Incorporated"),
    ("XOM", 34088, "Exxon Mobil Corporation"),
    ("CVX", 93410, "Chevron Corporation"),
    ("WMT", 104169, "Walmart Inc."),
    ("KO", 21344, "The Coca-Cola Company"),
    ("PG", 80424, "The Procter & Gamble Company"),
    ("CAT", 18230, "Caterpillar Inc."),
    ("BA", 12927, "The Boeing Company"),
    ("DIS", 1744489, "The Walt Disney Company"),
]


@dataclass(frozen=True)
class CorpusEntry:
    ticker: str
    cik: int
    company_name: str
    form: str
    accession: str
    primary_document: str
    period_end: date
    filed: date

    @property
    def document_id(self) -> str:
        return self.accession

    @property
    def fiscal_year(self) -> int:
        """Issuer convention: the calendar year in which the fiscal period ends."""
        return self.period_end.year

    @property
    def url(self) -> str:
        return ARCHIVE_URL.format(
            cik=self.cik,
            accession_nodash=self.accession.replace("-", ""),
            document=self.primary_document,
        )


def load_corpus(path: Path = CORPUS_PATH) -> list[CorpusEntry]:
    raw = tomllib.loads(path.read_text())
    return [
        CorpusEntry(
            ticker=f["ticker"],
            cik=int(f["cik"]),
            company_name=f["company_name"],
            form=f["form"],
            accession=f["accession"],
            primary_document=f["primary_document"],
            period_end=f["period_end"],
            filed=f["filed"],
        )
        for f in raw["filings"]
    ]


def render_corpus(entries: list[CorpusEntry]) -> str:
    lines = [
        "# Pinned corpus: one 10-K per company. Generated by `python -m ingest.corpus resolve`;",
        "# edit COMPANIES in ingest/corpus.py, not this file. fiscal_year = year of period_end.",
        "",
    ]
    for e in entries:
        lines += [
            "[[filings]]",
            f'ticker = "{e.ticker}"',
            f"cik = {e.cik}",
            f'company_name = "{e.company_name}"',
            f'form = "{e.form}"',
            f'accession = "{e.accession}"',
            f'primary_document = "{e.primary_document}"',
            f"period_end = {e.period_end.isoformat()}",
            f"filed = {e.filed.isoformat()}",
            "",
        ]
    return "\n".join(lines)


async def resolve_latest(user_agent: str, rps: float) -> list[CorpusEntry]:
    async with EdgarClient(user_agent=user_agent, requests_per_second=rps) as edgar:
        refs = await asyncio.gather(*(edgar.latest_filing(cik) for _, cik, _ in COMPANIES))
    return [
        CorpusEntry(
            ticker=ticker,
            cik=cik,
            company_name=name,
            form=ref.form,
            accession=ref.accession,
            primary_document=ref.primary_document,
            period_end=ref.period_end,
            filed=ref.filed,
        )
        for (ticker, cik, name), ref in zip(COMPANIES, refs, strict=True)
    ]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=["resolve", "show"])
    args = parser.parse_args()
    if args.command == "resolve":
        s = get_settings()
        entries = asyncio.run(resolve_latest(s.sec_user_agent, s.sec_requests_per_second))
        CORPUS_PATH.write_text(render_corpus(entries))
        print(f"wrote {len(entries)} filings to {CORPUS_PATH}")
    for e in load_corpus():
        print(f"{e.ticker:6} FY{e.fiscal_year}  period_end={e.period_end}  {e.accession}")


if __name__ == "__main__":
    main()
