"""Render results/vector_store_comparison.md from a saved benchmark run (no numbers typed by hand).

python -m bench.report results/bench/<ts>_vector_bench.json
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

OUT = Path("results/vector_store_comparison.md")
INTERPRETATION = Path("bench/interpretation.md")
NAMES = {"pgvector": "Cloud SQL pgvector", "vertex_vector_search": "Vertex AI Vector Search"}


def _lat(e: dict[str, Any], key: str) -> str:
    x = e[key]
    return f"{x['p50_ms']:.1f} / {x['p95_ms']:.1f} / {x['p99_ms']:.1f}"


def render(report: dict[str, Any], source: str) -> str:
    r, c, cost = report["results"], report["config"], report["monthly_cost_usd"]
    cfg = c
    lines = [
        "# Vector store comparison: Vertex AI Vector Search vs Cloud SQL pgvector",
        "",
        f"_Generated by `python -m bench.report` from [`{source}`]({Path(source).relative_to('results') if source.startswith('results/') else source})._",
        f"_Run: {report['started_at']} to {report['finished_at']}, environment: {report['environment']}._",
        "",
        "## Setup",
        "",
        f"- **Corpus:** {c['vectors']:,} chunks x {c['dim']}-d `{c['embedding_model']}` vectors (L2-normalised).",
        f"- **Queries:** {c['questions']} golden-set questions ({c['answerable']} answerable, used for recall).",
        "  Each question is embedded once, and the same vector is sent to both stores.",
        f"- **Latency:** {c['rounds']} rounds, run sequentially, alternating backend order per round, after warm-up.",
        f"- **pgvector:** {cfg['pgvector']}, on {cfg['cloud_sql']}.",
        f"- **Vector Search:** {cfg['vertex_vector_search']}.",
        f"- **Ground truth for ANN overlap:** {cfg['ground_truth']}.",
        "",
        "## Results",
        "",
        "| Backend | Scenario | Evidence recall@6 | recall@10 | ANN overlap@10 vs exact | Latency p50 / p95 / p99 (ms), incl. text | ANN call only (ms) |",
        "|---|---|---|---|---|---|---|",
    ]
    for b, scenarios in r.items():
        for sc, e in scenarios.items():
            overlap = (
                f"{e['ann_overlap@10_vs_exact']:.3f}" if "ann_overlap@10_vs_exact" in e else "—"
            )
            lines.append(
                f"| {NAMES.get(b, b)} | {sc.replace('_', ' ')} | {e['evidence_recall@6']:.3f} | {e['evidence_recall@10']:.3f} "
                f"| {overlap} | {_lat(e, 'latency_total')} | {_lat(e, 'latency_ann_only')} |"
            )
    lines += [
        "",
        'Vector Search\'s "incl. text" latency adds the Postgres lookup of chunk text and metadata,',
        "which the RAG service always needs. For pgvector the two columns are the same query.",
        "",
        "## Estimated monthly cost (list prices, us-central1, " + cost["prices_checked"] + ")",
        "",
        "| Item | USD / month |",
        "|---|---|",
        f"| Cloud SQL db-f1-micro + 10 GiB SSD (pgvector; needed either way as the system of record) | {cost['pgvector_cloud_sql_db_f1_micro_10gib_ssd']:.2f} |",
        f"| Vector Search: 1 x e2-standard-2 serving node | {cost['vector_search_1x_e2_standard_2']:.2f} |",
        f"| Vector Search: Private Service Connect endpoint | {cost['vector_search_psc_endpoint']:.2f} |",
        f"| **Vector Search incremental total** | **{cost['vector_search_total_serving']:.2f}** |",
        f"| One-off: index build / streaming inserts for {cost['index_size_gib']:.4f} GiB | {cost['vector_search_one_off_build_usd']:.4f} / {cost['vector_search_one_off_stream_insert_usd']:.4f} |",
        "",
        f"_{cost['note']}_",
        "",
    ]
    if INTERPRETATION.exists():  # human-written analysis of this run, kept next to the data
        lines += [INTERPRETATION.read_text().strip(), ""]
    return "\n".join(lines)


def main() -> None:
    src = sys.argv[1]
    report = json.loads(Path(src).read_text())
    OUT.write_text(render(report, src))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
